### ISSUE TITLE
embed.js 404 错误

### ISSUE THREAD

**Issue by Lruihao** [pengzhanbo/caniuse-embed#3]
以下 JS 都无法访问

- https://caniuse-embed.vercel.app/embed.js
- https://caniuse.pengzhanbo.cn/embed.js

应该是升级到 astro 5 导致的打包配置变更，我试着把 outDir 改为 `/dist/client/`，但是失败了。

https://docs.astro.build/zh-cn/guides/upgrade-to/v5/#changed-buildclient-and-buildserver-resolve-behavior

**Comment by pengzhanbo** [comment]
我在 astro5 推出的当天就升级了，我看了 astro5 的 changelog，没留意到这块的信息，看来还是太急躁了 😂

**Comment by pengzhanbo** [comment]
我仔细浏览了 astro@5 的变化以及相关的文档。astro 在构建阶段的生成产物发生了变化。在之前的版本中，将 embed.js 生成到 `dist/static` 目录中即可，集成中的 `vercel` 会将资源复制到 `.vercel/output/static` 中。
但在新版本发生了变化，构建产物先生成到了`dist/client` ，然后再复制到 `.vercel/output/static`，这导致了原来的在 `dist/static` 资源不再被处理，导致了 上传到 `vercel` 的资源不包含 `embed.js`。

**Comment by pengzhanbo** [comment]
该问题只需要修改 `astro.config.mjs` 中的 `integrations` 选项即可：
```diff
integrations: [
    {
      name: 'ciu-embed-scripts-bundle',
      hooks: {
        'astro:build:done': async ({ dir }) => {
          console.log('dir', dir)
--          const output = path.join(path.dirname(fileURLToPath(dir)), 'static')
++          const output = path.join(path.dirname(fileURLToPath(dir)), 'client')
```

**Comment by Lruihao** [comment]
> 该问题只需要修改 `astro.config.mjs` 中的 `integrations` 选项即可：

确实如此，我到时候整理一下 commit，在 #4 一起提交合并吧

**Comment by Lruihao** [comment]
额，本地运行时，`http://localhost:4321/embed.js` 还是没有，因为我基于本仓库的服务写了一个插件 [shortcode-caniuse](https://github.com/hugo-fixit/shortcode-caniuse) ，我在本地调试的时候会在那个服务中使用 `http://localhost:4321/embed.js` 进行调试。caniuse-embed 首页开发时引入的是未打包的代码，所以没有这个问题。

有没有办法让本地运行时，也能映射 `embed.js` 静态资源。

**Comment by pengzhanbo** [comment]
开发时并不会生成 embed.js ，因为 embed.ts 是直接导入到 index.astro 中的。
要在开发时使用，可以在 astro 中使用 vite 的 插件 API 生成一个 虚拟文件访问链接

**Comment by Lruihao** [comment]
> 开发时并不会生成 embed.js ，因为 embed.ts 是直接导入到 index.astro 中的。 要在开发时使用，可以在 astro 中使用 vite 的 插件 API 生成一个 虚拟文件访问链接

你能帮忙处理一下吗，我对 astro 以前没有了解过，今天才看了一下文档 😂

**Comment by pengzhanbo** [comment]
> 你能帮忙处理一下吗，我对 astro 以前没有了解过，今天才看了一下文档 😂

好的，我在当前的 PR 上处理。

**Comment by Lruihao** [comment]
> 好的，我在当前的 PR 上处理。

OK，感谢

**Comment by Lruihao** [comment]
我刚刚改了配置，`https://caniuse-embed-3ltq8cqc9-lrh-dev.vercel.app/embed.js` 在我的 vercel 上还是 404 呢，部署的配置应该是怎样的。`Output Directory`

<img width="920" alt="image" src="https://github.com/user-attachments/assets/9f8faa88-41ae-4cda-97d6-658031bae6ea">

**Comment by pengzhanbo** [comment]
框架预设为 astro 即可，其它配置项全部默认，即 override 全部关闭。

**Comment by Lruihao** [comment]
> 框架预设为 astro 即可，其它配置项全部默认，即 override 全部关闭。

```
integrations: [
    {
      name: 'ciu-embed-scripts-bundle',
      hooks: {
        'astro:build:done': async ({ dir }) => {
          console.log('dir', dir)
--          const output = path.join(path.dirname(fileURLToPath(dir)), 'static')
++          const output = path.join(path.dirname(fileURLToPath(dir)), 'client')
```

还是不行应该还是打包配置的问题，我最开始发现这个问题的时候，我就试过改成 'client'，但是打包后我发现 只有 `dist/client/` 中包含了 `embed.js`，它没有被复制到 `.vercel/output/static` 中。

会不会是 `"@astrojs/vercel` 的问题，我看到打包时有一个这样的警告：

```
The "@astrojs/vercel/serverless" import is deprecated and will be removed in a future release. Please import from "@astrojs/vercel" instead.
```

**Comment by pengzhanbo** [comment]
> 会不会是 "@astrojs/vercel 的问题，我看到打包时有一个这样的警告：

这个警告是 这个模块被弃用了，用新的方式代替。

我在本地打包，发现确实没有复制过去，这大概率和 astro5的 集合执行顺序有关，由于 自定义的集合晚于 vercel 集合执行导致没有成功。

两种方案：

1. 直接生成到 `.vercel/output/statc` 中。
2. 使用 vite 插件 api 的 buildEnd 在生成资源。

**Comment by pengzhanbo** [comment]
我在 PR 中更新了 `embed.js` 在开发时和构建时的生成方式，现在开发时和运行时都能正常获取了。

**Comment by Lruihao** [comment]
在更新最新的两次提交后，[embed.js](https://caniuse-embed.vercel.app/embed.js) 又变成404了。

// 另外，问一下 Vercel 的 ISR 需要在 Vercel 上设置吗，似乎我 fork 的它不会自己更新数据。

**Comment by pengzhanbo** [comment]
@Lruihao 
> 在更新最新的两次提交后，[embed.js](https://caniuse-embed.vercel.app/embed.js) 又变成404了。

我被 astro 的类型提示给骗了🤡... 在 `astro:build:setup` 钩子的参数中，类型提示支持 `updateConfig` 方法来更新配置，对其也是支持调用的，但是实际上它并不生效，只能回退使用 `vite.plugins.push` 的方式添加。

> // 另外，问一下 Vercel 的 ISR 需要在 Vercel 上设置吗，似乎我 fork 的它不会自己更新数据。

ISR 不生效的问题我也在排查中，它似乎跟它的文档所描述的有些不符。
